### ISSUE TITLE
Lacks Multi Platform Support

### ISSUE THREAD

**Issue by parth-verma** [ankitjain28may/getit#3]
The application lacks support for unix-based OSs like macOS and linux.

**Comment by ankitjain28may** [comment]
It supports linux (ubuntu) but i haven't tried on macOS

**Comment by parth-verma** [comment]
the path defined here ```path = "C:\\Users\\" + getuser() + "\\Downloads\\getit\\"``` makes it work for windows only since paths like these won't exist on unix based systems

**Comment by ankitjain28may** [comment]
Its default path, You can enter your path as per your wish.

**Comment by parth-verma** [comment]
But setting this default path in windows format will cause errors in cases when no path has been provided on a UNIX based OS

**Comment by ankitjain28may** [comment]
Yes, You need to provide the path in OS other than Windows.

**Comment by ankitjain28may** [comment]
If you would like to fix this, you can do this.

**Comment by tanmaysachan** [comment]
Issue resolved.
